### ISSUE TITLE
refmt integration

### ISSUE THREAD

**Issue by IwanKaramazow** [freebroccolo/vscode-reasonml#40]
I think it would be nice to provide `formatOnSave` powered by `refmt`. 
Made a local extension which does the job. If you want, I can submit a PR which integrates this
into `vscode-reasonml`.

**Comment by freebroccolo** [comment]
That sounds like a nice feature. A PR would be appreciated but it might be a little bit tricky to figure out how to base it on the existing formatting support. Otherwise I can just add it in the next release.

For what it's worth though, the `refmt` integration is currently part of [ocaml-language-server](https://github.com/freebroccolo/ocaml-language-server). You can get an idea of how it works by starting from [here](https://github.com/freebroccolo/ocaml-language-server/blob/e46df9a26118c3613ff5ccba35ea4848e3bc5a11/src/server/feature/documentFormatting.ts).

One way to implement this feature using the current formatting support would be to add a [custom server command](https://github.com/freebroccolo/ocaml-language-server/blob/master/src/shared/remote/server.ts) called `giveFormatted`.

On save, the `vscode-reasonml` client would send the request to the server (like [here](https://github.com/freebroccolo/vscode-reasonml/blob/master/src/client/command/doSplitCases.ts#L59)) and edit the document with the returned result. On the server side, you would set up a listener for this request that would call `command.getFormatted.refmt` like in the first link.

**Comment by IwanKaramazow** [comment]
Thanks for the code walkthrough. 
I submitted two PR's (one to `vscode-reasonml` & one to `ocaml-language-server`) which provide `refmt` on save support. Had to update the args of `refmt` to make it work with the latest `Reason`.

Due to the fact that Vscode doesn't support `pre`-save hooks, there's a strange piece of code in the `onSave`-lifecycle. I found a workaround in the `Go` vscode extension, see https://github.com/freebroccolo/vscode-reasonml/pull/41/files#diff-866c3b155d610a107da4d10be9df85c0R29

Feedback is welcome, I have no idea if this is right, but it seems to work...

**Comment by freebroccolo** [comment]
Thanks! At a glance, these look pretty good.

Regarding the save hook issue, would [`onWillSaveTextDocument`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4117) work for that? I think that was added somewhat recently.

**Comment by IwanKaramazow** [comment]
Found `onWillSaveTextDocument` too, but it doesn't seem to be released in 1.9.1 (latest version?) ?

**Comment by freebroccolo** [comment]
Hmm, weird. Either way it's not a big deal. I've gone ahead and merged the PRs for now. Can revisit the save issue later.

**Comment by IwanKaramazow** [comment]
Thanks for merging :) 
Can you also push the update to the vscode-store?

**Comment by freebroccolo** [comment]
No problem. I will probably do a release tomorrow since I need to push some other updates.

**Comment by freebroccolo** [comment]
Sorry for the delay in getting this released. I had to fix up some other issues before pushing a new version. It's available now in `0.0.98`. See the `"reason.formatOnSave"` setting to enable it.
