### ISSUE TITLE
Error, loses connection to [merlin?] server.

### ISSUE THREAD

**Issue by desmond-dsouza** [freebroccolo/vscode-reasonml#74]
On OSX: After updating bs-platform and re-installing reason-cli binaries, merlin / refmt functionality stops soon after starting VSCode. Output panel says:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/refmt ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Error - 12:15:46 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by freebroccolo** [comment]
From the error message it looks like `/usr/local/bin/refmt` is not in your `PATH`. Can you verify that it is? If you specified that location manually through the extension preferences, try unsetting it and see if it picks up the location automatically.

**Comment by desmond-dsouza** [comment]
It is in the path, no manual preferences set. Running with `nvm`, and the symlink from `/usr/local/bin/refmt` is actually absent. Plugin dies right after triggering refmt e.g. file save. 

I manually set the symlink & VSCode plugin now seems to stay up.

**Comment by desmond-dsouza** [comment]
Does the plugin depend on specific path `/usr/local/bin/refmt`?

**Comment by freebroccolo** [comment]
No, the plugin doesn't depend on any specific path for `refmt`. It will use whatever is in the environment.

It appears the problem was that when you upgraded those packages the symlink was broken and left in a bad state. VS Code doesn't know anything about this, it just calls `refmt` which resolves to `/usr/local/bin/refmt` but then that symlink points to nowhere so it fails.

There's not much I can do about this in the extension short of trying to check for bad symlinks, but that's sort of an unusual thing to do in general. This is really something that should be fixed upstream with the installers.

**Comment by freebroccolo** [comment]
Since it seems the issue was resolve I'm going to close this.
